services:
  web:
    build: .
    container_name: fastapi_app
    command: python main.py
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - mynetwork
    ports:
      - "8000:8000"    # <== هنا ربط البورت مهم جداً

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    container_name: redis_cache
    restart: always
    networks:
      - mynetwork

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
